name: Archive Stable Version
on:
  workflow_dispatch:

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: cpr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              throw Error('some error')
              const result = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: 'automerge',
                title: '[auto-created] Daily up-to-date main branch',
                head: 'release',
                base: 'main',
              });
              const mergeResult = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: result.data.number,
                merge_method: 'merge',
              })
              return {
                success: true
              }
            } catch (error) {
              return {
                success: false,
                error: error
              }
            }
      - name: Handle Error
        run: |
          echo "${{ steps.cpr.outputs.result }}"
          echo "${{ steps.cpr.outputs.result.error }}"
